name: Build Inews Release

on:
  pull_request:
         branches:
          - master
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
            cache: gradle

        - name: Add Secret Variables
          env:
            KEY_STORE: ${{ secrets.KEY_STORE }}
            KEY_STORE_ALIAS: ${{ secrets.KEY_STORE_ALIAS }}
            KEY_STORE_PASS:  ${{ secrets.KEY_STORE_PASS }}
            TEST_STRING: ${{ secrets.TEST_STRING }}
          run: |
                  bash  ./.github/workflows/set_local_properties.sh $KEY_STORE $KEY_STORE_ALIAS $KEY_STORE_PASS $TEST_STRING

        - name: Build Release
          run: bash ./gradlew clean build assembleRelease --stacktrace

        - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: App
            path: ${{ github.workspace}} /app/build/outputs/apk/release/app-release.apk
