name: Build Inews Release

on:
  pull_request:
         branches:
          - master
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
            cache: gradle

        - name: Add Secret Variables
          env:
            KEY_STORE: ${{ secrets.KEY_STORE }}
            KEY_STORE_ALIAS: ${{ secrets.KEY_STORE_ALIAS }}
            KEY_STORE_PASS:  ${{ secrets.KEY_STORE_PASS }}
            TEST_STRING: ${{ secrets.TEST_STRING }}
          run: |
            touch app.properties
            echo  KEY_STORE = $KEY_STORE >> app.properties
            echo  KEY_STORE_ALIAS = $KEY_STORE_ALIAS >> app.properties
            echo  KEY_STORE_PASS = $KEY_STORE_PASS >> app.properties
            echo  TEST_STRING= $TEST_STRING >> app.properties
            cat app.properties

        - name: Build Release
          run: bash ./gradlew clean build assembleRelease --stacktrace

        - name: Upload Lint Report
          uses: actions/upload-artifact@v2
          with:
            name: Lint Report
            path: ${{ github.workspace}}/app/build/reports/lint-results.html
